<a href="https://colab.research.google.com/github/thelbpandit0415/thelb-demo/blob/main/Diabetes_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
dataset = pd.read_csv('/content/diabetes.csv')

In [3]:
dataset.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [4]:
x = dataset.drop(columns='Outcome',axis=1)
y = dataset['Outcome']

In [5]:
print(x)
print(y)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [6]:
dataset.shape

(768, 9)

In [7]:
scaler=StandardScaler()

In [8]:
x = scaler.fit_transform(x)

In [9]:
x

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,stratify=y,random_state=2)

In [12]:
dataset.groupby('Outcome').mean()

         Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

In [13]:
print(x.shape,x_train.shape,x_test.shape)

(768, 8) (691, 8) (77, 8)

In [14]:
svm=svm.SVC(kernel='linear')

In [15]:
svm.fit(x_train,y_train)

SVC(kernel='linear')

In [16]:
x_train_prediction = svm.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)

In [17]:
print('Accuracy score of training data is: ',training_data_accuracy)

Accuracy score of training data is:  0.784370477568741

In [18]:
x_test_prediction = svm.predict(x_test)
training_data_accuracy_xtest = accuracy_score(x_test_prediction,y_test)

In [19]:
print('Accuracy score of x_test data is: ',training_data_accuracy_xtest)

Accuracy score of x_test data is:  0.7792207792207793

# **Making a predictive System**

In [31]:
input_data = (10,168,74,0,0,38,0.537,34)

#changing data in array
data_in_array = np.asarray(input_data)
reshaped_input_data = data_in_array.reshape(1,-1)
std_data=scaler.transform(reshaped_input_data)
prediction = svm.predict(std_data)
if (prediction[0]==0):
  print('The person is not diabetic')
else:
  print('The person is diabetic')

The person is diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(